<?php
declare(strict_types=1);

// EmailVerification SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

EmailVerificationUtility::setRegistrar(function (EmailVerificationUtility $u): void {
    $u->clean = [EmailVerificationClean::class, 'call'];
    $u->done = [EmailVerificationDone::class, 'call'];
    $u->make_error = [EmailVerificationMakeError::class, 'call'];
    $u->feature_add = [EmailVerificationFeatureAdd::class, 'call'];
    $u->feature_hook = [EmailVerificationFeatureHook::class, 'call'];
    $u->feature_init = [EmailVerificationFeatureInit::class, 'call'];
    $u->fetcher = [EmailVerificationFetcher::class, 'call'];
    $u->make_fetch_def = [EmailVerificationMakeFetchDef::class, 'call'];
    $u->make_context = [EmailVerificationMakeContext::class, 'call'];
    $u->make_options = [EmailVerificationMakeOptions::class, 'call'];
    $u->make_request = [EmailVerificationMakeRequest::class, 'call'];
    $u->make_response = [EmailVerificationMakeResponse::class, 'call'];
    $u->make_result = [EmailVerificationMakeResult::class, 'call'];
    $u->make_point = [EmailVerificationMakePoint::class, 'call'];
    $u->make_spec = [EmailVerificationMakeSpec::class, 'call'];
    $u->make_url = [EmailVerificationMakeUrl::class, 'call'];
    $u->param = [EmailVerificationParam::class, 'call'];
    $u->prepare_auth = [EmailVerificationPrepareAuth::class, 'call'];
    $u->prepare_body = [EmailVerificationPrepareBody::class, 'call'];
    $u->prepare_headers = [EmailVerificationPrepareHeaders::class, 'call'];
    $u->prepare_method = [EmailVerificationPrepareMethod::class, 'call'];
    $u->prepare_params = [EmailVerificationPrepareParams::class, 'call'];
    $u->prepare_path = [EmailVerificationPreparePath::class, 'call'];
    $u->prepare_query = [EmailVerificationPrepareQuery::class, 'call'];
    $u->graphql_body = [EmailVerificationGraphql::class, 'body'];
    $u->graphql_errors = [EmailVerificationGraphql::class, 'errors'];
    $u->result_basic = [EmailVerificationResultBasic::class, 'call'];
    $u->result_body = [EmailVerificationResultBody::class, 'call'];
    $u->result_headers = [EmailVerificationResultHeaders::class, 'call'];
    $u->transform_request = [EmailVerificationTransformRequest::class, 'call'];
    $u->transform_response = [EmailVerificationTransformResponse::class, 'call'];
});
